In [3]:
import numpy as np

In [5]:
lambda_ref = 1239.8/870.0*1e-9

Ax_inverse = np.zeros((2, 2)) 
Ax_inverse[:, 0] = np.array([15, -142e6*lambda_ref])
Ax_inverse[:, 1] = np.array([23, 115e6*lambda_ref])

Ax = np.linalg.inv(Ax_inverse)

Ay_inverse = np.zeros((2, 2)) 
Ay_inverse[:, 0] = np.array([13.3, -120e6*lambda_ref]) 
Ay_inverse[:, 1] = np.array([16.7, 83e6*lambda_ref])

Ay = np.linalg.inv(Ay_inverse)

In [6]:
Ax

array([[ 0.02304147, -3.23376076],
       [ 0.02845121,  2.10897441]])

In [7]:
Ay

array([[ 0.02670614, -3.77065723],
       [ 0.03861128,  3.00297852]])

In [8]:
np.savez('calibration/tmo_IP1.npz',Ax=Ax,Ay=Ay)

In [9]:
test = np.load('calibration/tmo_IP1.npz')

In [12]:
print(test.files)

['Ax', 'Ay']


In [13]:
test['Ax']

array([[ 0.02304147, -3.23376076],
       [ 0.02845121,  2.10897441]])

In [14]:
test['Ay']

array([[ 0.02670614, -3.77065723],
       [ 0.03861128,  3.00297852]])